# Generated by Django 3.0 on 2021-02-16 23:58

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FooVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField(null=True)),
                ('value', models.FloatField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='temporal.Foo')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('temporal', django.db.models.manager.Manager()),
            ],
        ),
    ]
