# Generated by Django 3.0 on 2021-02-17 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporal', '0002_auto_20210217_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooversion',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporal', to='temporal.Foo'),
        ),
        migrations.AlterField(
            model_name='fooversion',
            name='sys_start_date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='FooTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='temporal.Foo')),
            ],
        ),
    ]
