# Generated by Django 3.0 on 2021-02-18 19:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporal', '0003_auto_20210217_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('sys_start_date', models.DateTimeField()),
                ('sys_end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
            ],
            options={
                'ordering': ('valid_start_date',),
                'abstract': False,
                'unique_together': {('id', 'identity')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleDay',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('identity', models.UUIDField()),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('sys_start_date', models.DateTimeField()),
                ('sys_end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('day', models.CharField(choices=[('SAT', 'Saturday'), ('SUN', 'Sunday'), ('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], default='SAT', max_length=3)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='temporal.Schedule')),
            ],
            options={
                'ordering': ('valid_start_date',),
                'abstract': False,
                'unique_together': {('id', 'identity')},
            },
        ),
        migrations.RemoveField(
            model_name='footimestamp',
            name='identity',
        ),
        migrations.RemoveField(
            model_name='fooversion',
            name='identity',
        ),
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.DeleteModel(
            name='FooTimestamp',
        ),
        migrations.DeleteModel(
            name='FooVersion',
        ),
    ]
