# Generated by Django 3.0 on 2021-03-22 23:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('temporal', '0004_auto_20210218_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Foo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FooTimestamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='temporal.Foo')),
            ],
        ),
        migrations.CreateModel(
            name='FooVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('sys_start_date', models.DateTimeField()),
                ('sys_end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('value', models.FloatField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='temporal', to='temporal.Foo')),
            ],
            options={
                'ordering': ('valid_start_date',),
                'abstract': False,
            },
            managers=[
                ('temporal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='scheduleday',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scheduleday',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleDay',
        ),
    ]
