# Generated by Django 3.0 on 2021-03-30 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('temporal', '0005_auto_20210322_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Baz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BazVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_start_date', models.DateField()),
                ('valid_end_date', models.DateField()),
                ('sys_start_date', models.DateTimeField()),
                ('sys_end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999))),
                ('value', models.FloatField(default=0)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='temporal.Baz')),
            ],
            options={
                'ordering': ('valid_start_date',),
                'abstract': False,
            },
            managers=[
                ('temporal', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='fooversion',
            name='identity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='temporal.Foo'),
        ),
        migrations.DeleteModel(
            name='FooTimestamp',
        ),
    ]
