# Generated by Django 3.0 on 2021-03-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temporal', '0006_auto_20210330_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='bar',
            name='foo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bars', to='temporal.Foo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bar',
            name='name',
            field=models.CharField(default='default_name', max_length=32),
            preserve_default=False,
        ),
    ]
